### ISSUE TITLE
 Enumerate other 3 factors that could have been studied in the paper and why you think they would belong to good/bad practice, Exercise 3.3

### ISSUE THREAD

**Issue by LilideBree** [jimhommes/BubbleBobble#164]

**Comment by JPluim** [comment]
Can somebody check my ideas? If I understood the question correct, I had to come up with three good/bad practices myself, but not completely sure whether my ideas are correct. Using branch assignment3_SSE

**Comment by LilideBree** [comment]
Done in documentation.

<documentation
