### ISSUE TITLE
Describe in detail 3 bad practice factors and why they belong to the bad practice group, Exercise 3.4

### ISSUE THREAD

**Issue by LilideBree** [jimhommes/BubbleBobble#165]

**Comment by JPluim** [comment]
Can someone review this question? The paper doesn't really describe the reasons because of what certain factors are good or bad practices, so I think we have to describe our own ideas on this matter in this question. Using branch assignment3_SSE.

**Comment by LilideBree** [comment]
Done in documentation.

<documentation
